#!/usr/bin/env bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

list_versions() {
  local filter="cat"
  if [ -n "$version_pattern" ]; then
    filter="egrep ${version_pattern}"
  fi
  apt-cache madison $package | awk '{print $3}' | $filter | tac
}

latest_version() {
  list_versions | tail -1
}

payload=$(mktemp /tmp/artifactory-deb.XXXXXX)
cat > $payload <&0

package=$(attr source package)
version_pattern=$(jq -r '.source.version_pattern // ""' < $payload)
version_number=$(jq -r '.version.number // ""' < $payload)

add_keys
deb_source > /etc/apt/sources.list
rm -rf /var/lib/apt/lists/*
apt-get update -y

if [ -z "$version_number" ]; then
  list_versions | jq -R '.' | jq -s "map({number: .})" >&3
else
  latest_version | jq -R '.' | jq -s "map({number: .})" >&3
fi
