#!/usr/bin/env bash

set -ex

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

payload=$(mktemp /tmp/artifactory-deb.XXXXXX)
cat > $payload <&0

version_number=$(jq -r '.version.number // ""' < $payload)

deb_source > /etc/apt/sources.list
apt-get update -y

if [ -z "$version_number" ]; then
  list_versions | jq -R '.' | jq -s "map({number: .})" >&3
else
  latest_version | jq -R '.' | jq -s "map({number: .})" >&3
fi
