#!/usr/bin/env bash

set -ex

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

source=$1
cd $source

payload=$(mktemp /tmp/artifactory-deb.XXXXXX)
cat > $payload <&0

assemble_properties() {
  echo "deb.component=$component;deb.distribution=$distribution;deb.architecture=$architecture"
}

assemble_url() {
  local deb=$1
  echo "$repository/$components_dir/$deb;$(assemble_properties)"
}

put() {
  local deb=$1
  local url="$(assemble_url $deb)"

  echo "PUT $url"
  echo "$password" | curl -u$username -XPUT -T $deb $url
}

version_for() {
  local deb=$1
  dpkg-deb -I $deb | grep Version | awk '{print $2}'
}

extract_version() {
  # Ensure all supplied debs have the same version
  for f in $(ls *.deb); do
    local v=$(version_for $deb)
    if [ -z "$version" ]; then
      local version=$v
    else
      test "$version" = "$v" || { echo "Debs must not be of mixed versions. Found $version, $v" >&2; exit 1; }
    fi
  done

  echo $version
}

repository=$(attr source repository)
username=$(attr source username)
password=$(attr source password)
distribution=$(attr source distribution)
debs=$(attr params debs)

component=$(jq -r '.source.component // "main"' < $payload)
components_dir=$(jq -r '.source.components_dir // "pool"' < $payload)
architecture=$(jq -r '.source.architecture // "amd64"' < $payload)

cd $source/$debs

version=$(extract_version)

for f in $(ls *.deb); do
  put $f
done

jq -n "{
  version: {
    number: \"$version\"
  }
}" >&3
